linters:
  disable-all: true
  enable:
    - bodyclose
    # - deadcode
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    # - structcheck
    - stylecheck
    # - typecheck
    - unconvert
    - unparam
    - unused
    # - varcheck
    - whitespace
    - asciicheck
    - gocognit
    - godot
    - godox
    # - goerr113
    - nestif
    - prealloc
    - revive
  # don't enable:
    # - scopelint
    # - gochecknoglobals
    # - interfacer
    # - maligned
    # - testpackage
    # - wsl

run:
  relative-path-mode: gomod
  concurrency: 4
  timeout: 1m
  go: '1.17'

linters-settings:
  # revive:
  #   ignore-generated-header: true
  #   severity: warning
  #   rules:
  #     - name: atomic
  #     - name: line-length-limit
  #       severity: error
  #       arguments: [80]
  #     - name: unhandled-error
  #       arguments : ["fmt.Printf", "myFunction"]

  gosec:
    excludes:
      - G505
      - G401

  lll:
    line-length: 140 

  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        # deny:
        #   - pkg: io/ioutil
        #     desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"


